TOP = ..
include $(TOP)/configure/CONFIG
## Temporarilly commented out to work wround errors in builder extension preventing building of module
#DIRS := $(DIRS) $(filter-out $(DIRS), $(wildcard makeIocs))
#DIRS := $(DIRS) $(filter-out $(DIRS), $(wildcard makeDocumentation))
#DIRS := $(DIRS) $(filter-out $(DIRS), $(wildcard simulations))
include $(TOP)/configure/RULES_DIRS
