TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

DB += mks937b.template
DB += mks937bRelays.template
DB += mks937bFastRelay.template
DB += mks937bPirg.template
DB += mks937bPirgGroup.template
DB += mks937bPirgDummy.template
DB += mks937bImg.template
DB += mks937bImgGroup.template
DB += mks937bImgMean.template
DB += mks937bImgDummy.template
DB += mks937bGauge.template
DB += mks937bGauge_rio.template
DB += mks937bGaugeGroup.template
DB += mks937bInterlock.template
DB += mks937bHcg.template
DB += mks937bHcgGroup.template

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
